-- Icon list for PCP custom buttons.
-- Paths below are intentionally kept to old/common WoW icon names so they work in 1.12 as well.
PCP_IconList = {
    { name = "Question Mark", path = "Interface\\Icons\\INV_Misc_QuestionMark" },
    { name = "Gear", path = "Interface\\Icons\\INV_Misc_Gear_01" },
    { name = "Cog", path = "Interface\\Icons\\Trade_Engineering" },
    { name = "Bag", path = "Interface\\Icons\\INV_Misc_Bag_08" },
    { name = "Book", path = "Interface\\Icons\\INV_Misc_Book_09" },
    { name = "Scroll", path = "Interface\\Icons\\INV_Scroll_03" },
    { name = "Key", path = "Interface\\Icons\\INV_Misc_Key_03" },
    { name = "Coin", path = "Interface\\Icons\\INV_Misc_Coin_01" },
    { name = "Skull", path = "Interface\\TargetingFrame\\UI-RaidTargetingIcon_8" },
    { name = "Cross", path = "Interface\\TargetingFrame\\UI-RaidTargetingIcon_7" },
    { name = "Square", path = "Interface\\TargetingFrame\\UI-RaidTargetingIcon_6" },
    { name = "Moon", path = "Interface\\TargetingFrame\\UI-RaidTargetingIcon_5" },
    { name = "Triangle", path = "Interface\\TargetingFrame\\UI-RaidTargetingIcon_4" },
    { name = "Diamond", path = "Interface\\TargetingFrame\\UI-RaidTargetingIcon_3" },
    { name = "Circle", path = "Interface\\TargetingFrame\\UI-RaidTargetingIcon_2" },
    { name = "Star", path = "Interface\\TargetingFrame\\UI-RaidTargetingIcon_1" },
    { name = "Paladin Kings", path = "Interface\\Icons\\Spell_Magic_GreaterBlessingofKings" },
    { name = "Paladin Might", path = "Interface\\Icons\\Spell_Holy_GreaterBlessingofKings" },
    { name = "Paladin Wisdom", path = "Interface\\Icons\\Spell_Holy_GreaterBlessingofWisdom" },
    { name = "Paladin Light", path = "Interface\\Icons\\Spell_Holy_GreaterBlessingofLight" },
    { name = "Paladin Salvation", path = "Interface\\Icons\\Spell_Holy_GreaterBlessingofSalvation" },
    { name = "Holy Light", path = "Interface\\Icons\\Spell_Holy_HolyBolt" },
    { name = "Flash Heal", path = "Interface\\Icons\\Spell_Holy_FlashHeal" },
    { name = "Shield", path = "Interface\\Icons\\Spell_Holy_PowerWordShield" },
    { name = "Resurrection", path = "Interface\\Icons\\Spell_Holy_Resurrection" },
    { name = "Cleanse", path = "Interface\\Icons\\Spell_Holy_Renew" },
    { name = "Seal Command", path = "Interface\\Icons\\Ability_Warrior_InnerRage" },
    { name = "Divine Shield", path = "Interface\\Icons\\Spell_Holy_DivineIntervention" },
    { name = "Judgement", path = "Interface\\Icons\\Spell_Holy_RighteousFury" },
    { name = "Concentration Aura", path = "Interface\\Icons\\Spell_Holy_MindSooth" },
    { name = "Retribution Aura", path = "Interface\\Icons\\Spell_Holy_AuraOfLight" },
    { name = "Devotion Aura", path = "Interface\\Icons\\Spell_Holy_DevotionAura" },
    { name = "Priest Heal", path = "Interface\\Icons\\Spell_Holy_Heal" },
    { name = "Priest Renew", path = "Interface\\Icons\\Spell_Holy_Renew" },
    { name = "Priest Fortitude", path = "Interface\\Icons\\Spell_Holy_WordFortitude" },
    { name = "Priest Spirit", path = "Interface\\Icons\\Spell_Holy_DivineSpirit" },
    { name = "Priest Shadowform", path = "Interface\\Icons\\Spell_Shadow_Shadowform" },
    { name = "Priest Dispel", path = "Interface\\Icons\\Spell_Holy_DispelMagic" },
    { name = "Priest Prayer", path = "Interface\\Icons\\Spell_Holy_PrayerOfHealing02" },
    { name = "Priest Fear Ward", path = "Interface\\Icons\\Spell_Holy_Excorcism" },
    { name = "Priest Mind Blast", path = "Interface\\Icons\\Spell_Shadow_UnholyFrenzy" },
    { name = "Priest Mind Control", path = "Interface\\Icons\\Spell_Shadow_ShadowWordDominate" },
    { name = "Shaman Windfury", path = "Interface\\Icons\\Spell_Nature_Windfury" },
    { name = "Shaman Grace of Air", path = "Interface\\Icons\\Spell_Nature_InvisibilityTotem" },
    { name = "Shaman Tranquil Air", path = "Interface\\Icons\\Spell_Nature_Brilliance" },
    { name = "Nature Resistance", path = "Interface\\Icons\\Spell_Nature_NatureResistanceTotem" },
    { name = "Strength of Earth", path = "Interface\\Icons\\Spell_Nature_EarthBindTotem" },
    { name = "Stoneskin", path = "Interface\\Icons\\Spell_Nature_StoneSkinTotem" },
    { name = "Earthbind", path = "Interface\\Icons\\Spell_Nature_StrengthOfEarthTotem02" },
    { name = "Tremor", path = "Interface\\Icons\\Spell_Nature_TremorTotem" },
    { name = "Searing", path = "Interface\\Icons\\Spell_Fire_SearingTotem" },
    { name = "Magma", path = "Interface\\Icons\\Spell_Fire_SelfDestruct" },
    { name = "Fire Nova", path = "Interface\\Icons\\Spell_Fire_SealOfFire" },
    { name = "Flametongue", path = "Interface\\Icons\\Spell_Nature_GuardianWard" },
    { name = "Frost Resistance", path = "Interface\\Icons\\Spell_FrostResistanceTotem_01" },
    { name = "Mana Spring", path = "Interface\\Icons\\Spell_Nature_ManaRegenTotem" },
    { name = "Healing Stream", path = "Interface\\Icons\\INV_Spear_04" },
    { name = "Poison Cleansing", path = "Interface\\Icons\\Spell_Nature_PoisonCleansingTotem" },
    { name = "Disease Cleansing", path = "Interface\\Icons\\Spell_Nature_DiseaseCleansingTotem" },
    { name = "Fire Resistance", path = "Interface\\Icons\\Spell_FireResistanceTotem_01" },
    { name = "Mana Tide", path = "Interface\\Icons\\Spell_Frost_SummonWaterElemental" },
    { name = "Shaman Lightning Bolt", path = "Interface\\Icons\\Spell_Nature_Lightning" },
    { name = "Shaman Chain Lightning", path = "Interface\\Icons\\Spell_Nature_ChainLightning" },
    { name = "Shaman Healing Wave", path = "Interface\\Icons\\Spell_Nature_MagicImmunity" },
    { name = "Shaman Reincarnation", path = "Interface\\Icons\\Spell_Nature_Reincarnation" },
    { name = "Shaman Ghost Wolf", path = "Interface\\Icons\\Spell_Nature_SpiritWolf" },
    { name = "Shaman Purge", path = "Interface\\Icons\\Spell_Nature_Purge" },
    { name = "Warrior Charge", path = "Interface\\Icons\\Ability_Warrior_Charge" },
    { name = "Warrior Taunt", path = "Interface\\Icons\\Spell_Nature_Reincarnation" },
    { name = "Defensive Stance", path = "Interface\\Icons\\Ability_Warrior_DefensiveStance" },
    { name = "Battle Stance", path = "Interface\\Icons\\Ability_Warrior_OffensiveStance" },
    { name = "Berserker Stance", path = "Interface\\Icons\\Ability_Racial_Avatar" },
    { name = "Bloodrage", path = "Interface\\Icons\\Ability_Racial_BloodRage" },
    { name = "Execute", path = "Interface\\Icons\\INV_Sword_48" },
    { name = "Shield Wall", path = "Interface\\Icons\\Ability_Warrior_ShieldWall" },
    { name = "Shield Bash", path = "Interface\\Icons\\Ability_Warrior_ShieldBash" },
    { name = "Sunder Armor", path = "Interface\\Icons\\Ability_Warrior_Sunder" },
    { name = "Heroic Strike", path = "Interface\\Icons\\Ability_Rogue_Ambush" },
    { name = "Thunder Clap", path = "Interface\\Icons\\Ability_ThunderClap" },
    { name = "Rend", path = "Interface\\Icons\\Ability_Gouge" },
    { name = "Hamstring", path = "Interface\\Icons\\Ability_ShockWave" },
    { name = "Whirlwind", path = "Interface\\Icons\\Ability_Whirlwind" },
    { name = "Mortal Strike", path = "Interface\\Icons\\Ability_Warrior_SavageBlow" },
    { name = "Hunter Mark", path = "Interface\\Icons\\Ability_Hunter_SniperShot" },
    { name = "Hunter Pet", path = "Interface\\Icons\\Ability_Hunter_BeastCall" },
    { name = "Hunter Trap", path = "Interface\\Icons\\Spell_Frost_ChainsOfIce" },
    { name = "Hunter Aspect", path = "Interface\\Icons\\Ability_Mount_JungleTiger" },
    { name = "Hunter Auto Shot", path = "Interface\\Icons\\Ability_Whirlwind" },
    { name = "Hunter Multi Shot", path = "Interface\\Icons\\Ability_UpgradeMoonGlaive" },
    { name = "Hunter Aimed Shot", path = "Interface\\Icons\\INV_Spear_07" },
    { name = "Hunter Feign Death", path = "Interface\\Icons\\Ability_Rogue_FeignDeath" },
    { name = "Hunter Wing Clip", path = "Interface\\Icons\\Ability_Rogue_Trip" },
    { name = "Hunter Rapid Fire", path = "Interface\\Icons\\Ability_Hunter_RunningShot" },
    { name = "Hunter Beast Lore", path = "Interface\\Icons\\Ability_Physical_Taunt" },
    { name = "Hunter Eagle Eye", path = "Interface\\Icons\\Ability_Hunter_EagleEye" },
    { name = "Rogue Stealth", path = "Interface\\Icons\\Ability_Stealth" },
    { name = "Rogue Kick", path = "Interface\\Icons\\Ability_Kick" },
    { name = "Rogue Sap", path = "Interface\\Icons\\Ability_Sap" },
    { name = "Rogue Backstab", path = "Interface\\Icons\\Ability_BackStab" },
    { name = "Rogue Cheap Shot", path = "Interface\\Icons\\Ability_CheapShot" },
    { name = "Rogue Eviscerate", path = "Interface\\Icons\\Ability_Rogue_Eviscerate" },
    { name = "Rogue Sinister Strike", path = "Interface\\Icons\\Spell_Shadow_RitualOfSacrifice" },
    { name = "Rogue Sprint", path = "Interface\\Icons\\Ability_Rogue_Sprint" },
    { name = "Rogue Vanish", path = "Interface\\Icons\\Ability_Vanish" },
    { name = "Rogue Pick Lock", path = "Interface\\Icons\\Spell_Nature_MoonKey" },
    { name = "Rogue Poison", path = "Interface\\Icons\\Ability_Poisons" },
    { name = "Rogue Ambush", path = "Interface\\Icons\\Ability_Rogue_Ambush" },
    { name = "Mage Frostbolt", path = "Interface\\Icons\\Spell_Frost_FrostBolt02" },
    { name = "Mage Fireball", path = "Interface\\Icons\\Spell_Fire_FlameBolt" },
    { name = "Mage Arcane", path = "Interface\\Icons\\Spell_Holy_MagicalSentry" },
    { name = "Mage Polymorph", path = "Interface\\Icons\\Spell_Nature_Polymorph" },
    { name = "Mage Blizzard", path = "Interface\\Icons\\Spell_Frost_IceStorm" },
    { name = "Mage Fire Blast", path = "Interface\\Icons\\Spell_Fire_Fireball" },
    { name = "Mage Flamestrike", path = "Interface\\Icons\\Spell_Fire_SelfDestruct" },
    { name = "Mage Frost Nova", path = "Interface\\Icons\\Spell_Frost_FrostNova" },
    { name = "Mage Ice Block", path = "Interface\\Icons\\Spell_Frost_Frost" },
    { name = "Mage Arcane Intellect", path = "Interface\\Icons\\Spell_Holy_MagicalSentry" },
    { name = "Mage Evocation", path = "Interface\\Icons\\Spell_Nature_Purge" },
    { name = "Mage Counterspell", path = "Interface\\Icons\\Spell_Frost_IceShock" },
    { name = "Mage Portal", path = "Interface\\Icons\\Spell_Arcane_PortalIronForge" },
    { name = "Mage Food", path = "Interface\\Icons\\INV_Misc_Food_10" },
    { name = "Mage Water", path = "Interface\\Icons\\INV_Drink_18" },
    { name = "Warlock Shadowbolt", path = "Interface\\Icons\\Spell_Shadow_ShadowBolt" },
    { name = "Warlock Fear", path = "Interface\\Icons\\Spell_Shadow_Possession" },
    { name = "Warlock Imp", path = "Interface\\Icons\\Spell_Shadow_SummonImp" },
    { name = "Warlock Healthstone", path = "Interface\\Icons\\INV_Stone_04" },
    { name = "Warlock Soulstone", path = "Interface\\Icons\\Spell_Shadow_SoulGem" },
    { name = "Warlock Curse", path = "Interface\\Icons\\Spell_Shadow_CurseOfAchimonde" },
    { name = "Warlock Corruption", path = "Interface\\Icons\\Spell_Shadow_AbominationExplosion" },
    { name = "Warlock Life Tap", path = "Interface\\Icons\\Spell_Shadow_BurningSpirit" },
    { name = "Warlock Drain Life", path = "Interface\\Icons\\Spell_Shadow_LifeDrain02" },
    { name = "Warlock Summon Voidwalker", path = "Interface\\Icons\\Spell_Shadow_SummonVoidWalker" },
    { name = "Warlock Summon Succubus", path = "Interface\\Icons\\Spell_Shadow_SummonSuccubus" },
    { name = "Warlock Summon Felhunter", path = "Interface\\Icons\\Spell_Shadow_SummonFelHunter" },
    { name = "Warlock Rain of Fire", path = "Interface\\Icons\\Spell_Shadow_RainOfFire" },
    { name = "Druid Bear", path = "Interface\\Icons\\Ability_Racial_BearForm" },
    { name = "Druid Cat", path = "Interface\\Icons\\Ability_Druid_CatForm" },
    { name = "Druid Rejuvenation", path = "Interface\\Icons\\Spell_Nature_Rejuvenation" },
    { name = "Druid Mark", path = "Interface\\Icons\\Spell_Nature_Regeneration" },
    { name = "Druid Innervate", path = "Interface\\Icons\\Spell_Nature_Lightning" },
    { name = "Druid Moonfire", path = "Interface\\Icons\\Spell_Nature_StarFall" },
    { name = "Druid Wrath", path = "Interface\\Icons\\Spell_Nature_AbolishMagic" },
    { name = "Druid Starfire", path = "Interface\\Icons\\Spell_Arcane_StarFire" },
    { name = "Druid Healing Touch", path = "Interface\\Icons\\Spell_Nature_HealingTouch" },
    { name = "Druid Regrowth", path = "Interface\\Icons\\Spell_Nature_ResistNature" },
    { name = "Druid Tranquility", path = "Interface\\Icons\\Spell_Nature_Tranquility" },
    { name = "Druid Travel", path = "Interface\\Icons\\Ability_Druid_TravelForm" },
    { name = "Druid Aquatic", path = "Interface\\Icons\\Ability_Druid_AquaticForm" },
    { name = "Druid Entangling Roots", path = "Interface\\Icons\\Spell_Nature_StrangleVines" },
    { name = "Attack", path = "Interface\\Icons\\Ability_Warrior_Charge" },
    { name = "Stop", path = "Interface\\Icons\\Spell_Shadow_DeathScream" },
    { name = "Come", path = "Interface\\Icons\\Spell_Nature_SpiritWolf" },
    { name = "Move", path = "Interface\\Icons\\Ability_Rogue_Sprint" },
    { name = "Stay", path = "Interface\\Icons\\Ability_Hunter_Pathfinding" },
    { name = "Pause", path = "Interface\\Icons\\Spell_Frost_Stun" },
    { name = "Unpause", path = "Interface\\Icons\\Spell_Holy_Renew" },
    { name = "AOE", path = "Interface\\Icons\\Spell_Fire_SelfDestruct" },
    { name = "Distance", path = "Interface\\Icons\\Ability_Hunter_Quickshot" },
    { name = "Mount", path = "Interface\\Icons\\Ability_Mount_RidingHorse" },
    { name = "Follow", path = "Interface\\Icons\\Ability_Hunter_AspectOfTheMonkey" },
    { name = "Assist", path = "Interface\\Icons\\Ability_DualWield" },
    { name = "Defend", path = "Interface\\Icons\\INV_Shield_04" },
    { name = "Loot", path = "Interface\\Icons\\INV_Box_01" },
    { name = "Trade", path = "Interface\\Icons\\INV_Misc_Coin_02" },
    { name = "Repair", path = "Interface\\Icons\\Trade_BlackSmithing" },
    { name = "Target", path = "Interface\\Icons\\Ability_Hunter_SniperShot" },
    { name = "Pull", path = "Interface\\Icons\\Ability_Marksmanship" },
    { name = "Skull Command", path = "Interface\\Icons\\INV_Misc_Bone_ElfSkull_01" },
    { name = "Group", path = "Interface\\Icons\\INV_Banner_03" },
    { name = "Party", path = "Interface\\Icons\\Spell_Holy_PrayerOfHealing02" },
    { name = "Raid", path = "Interface\\Icons\\INV_Helmet_06" },
    { name = "Sword", path = "Interface\\Icons\\INV_Sword_04" },
    { name = "Axe", path = "Interface\\Icons\\INV_Axe_01" },
    { name = "Mace", path = "Interface\\Icons\\INV_Mace_01" },
    { name = "Dagger", path = "Interface\\Icons\\INV_Weapon_ShortBlade_05" },
    { name = "Staff", path = "Interface\\Icons\\INV_Staff_08" },
    { name = "Bow", path = "Interface\\Icons\\INV_Weapon_Bow_02" },
    { name = "Gun", path = "Interface\\Icons\\INV_Weapon_Rifle_01" },
    { name = "Wand", path = "Interface\\Icons\\INV_Wand_01" },
    { name = "Shield Item", path = "Interface\\Icons\\INV_Shield_05" },
    { name = "Helmet", path = "Interface\\Icons\\INV_Helmet_03" },
    { name = "Chest", path = "Interface\\Icons\\INV_Chest_Chain" },
    { name = "Boots", path = "Interface\\Icons\\INV_Boots_05" },
    { name = "Gloves", path = "Interface\\Icons\\INV_Gauntlets_04" },
    { name = "Ring", path = "Interface\\Icons\\INV_Jewelry_Ring_03" },
    { name = "Trinket", path = "Interface\\Icons\\INV_Misc_Orb_01" },
    { name = "Food", path = "Interface\\Icons\\INV_Misc_Food_15" },
    { name = "Drink", path = "Interface\\Icons\\INV_Drink_05" },
    { name = "Bandage", path = "Interface\\Icons\\INV_Misc_Bandage_15" },
    { name = "Potion Red", path = "Interface\\Icons\\INV_Potion_54" },
    { name = "Potion Blue", path = "Interface\\Icons\\INV_Potion_76" },
    { name = "Potion Green", path = "Interface\\Icons\\INV_Potion_45" },
    { name = "Hearthstone", path = "Interface\\Icons\\INV_Misc_Rune_01" },
    { name = "Campfire", path = "Interface\\Icons\\Spell_Fire_Fire" },
    { name = "Fishing", path = "Interface\\Icons\\Trade_Fishing" },
    { name = "Mining", path = "Interface\\Icons\\Trade_Mining" },
    { name = "Herbalism", path = "Interface\\Icons\\Spell_Nature_NatureTouchGrow" },
    { name = "Alchemy", path = "Interface\\Icons\\Trade_Alchemy" },
    { name = "First Aid", path = "Interface\\Icons\\Spell_Holy_SealOfSacrifice" },
    { name = "Cooking", path = "Interface\\Icons\\INV_Misc_Food_15" },
}
